sudo: required
dist: trusty
language: go
go: 1.9.x

matrix:
  include:
    - os: linux
    - os: osx
      # Do not start osx build for PR
      if: type != pull_request

env:
  global:
    - ELECTRON_CACHE: $HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE: $HOME/.cache/electron-builder
    - BUILD_DIR: dist
    - BUILDLIB_DIR: $BUILD_DIR/libskycoin
    - LIB_DIR: lib

cache:
  yarn: true
  directories:
  - electron/node_modules
  - electron/src/node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  - $HOME/.npm/_prebuilds

install:
  # Install gox
  - go get github.com/gz-c/gox
  # Install dependences for building wallet
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_PULL_REQUEST" == false ]]; then sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils  &&nvm install 8; fi
  # for test
  - go get -t ./...
  - make install-linters
  # TODO: Install dependencies for testing libskycoin

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$TRAVIS_PULL_REQUEST" == false ]]; then ./ci-scripts/add-key.sh && npm install -g yarn ;fi

script:
  - gometalinter --disable-all -E goimports --tests --vendor ./...
  - vendorcheck ./...
  - GOARCH=386 go test ./...
  - GOARCH=amd64 go test ./...
  # stable integration tests
  - make integration-test-stable
  # build wallets
  - if [[ "$TRAVIS_PULL_REQUEST" == false ]]; then ./ci-scripts/build-wallet.sh; fi
  # build libskycoin
  - mkdir -p $BUILDLIB_DIR
  - rm -Rf $BUILDLIB_DIR/*
  - go build -buildmode=c-archive -o $BUILDLIB_DIR/libskycoin.a  $LIB_DIR/cgo/main.go
  # test libskycoin
  - cp $LIB_DIR/cgo/tests/*.c $BUILDLIB_DIR/
  - gcc -o $BUILDLIB_DIR/test_libskycoin $BUILDLIB_DIR/*.c -I$BUILDLIB_DIR -lcriterion -lskycoin -L $BUILDLIB_DIR
  - $(BUILDLIB_DIR)/test_libskycoin
  # TODO: test pyskycoin
  # - go build -buildmode=c-shared  -o $BUILDLIB_DIR/libskycoin.so $LIB_DIR/cgo/main.go
   

notifications:
  email: false

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_BUCKET
  skip_cleanup: true
  local_dir: electron/release
  upload-dir: wallet
  acl: public_read
  region: $AWS_REGION
  on:
    repo: skycoin/skycoin
    branch: master
