sudo: required
dist: trusty
language: go
go:
  - "1.11.x"

matrix:
  include:
    - os: linux
      env: VERSION_UPGRADE_TEST_WAIT_TIMEOUT=45s
    - os: osx
      # Do not start osx build for PR
      if: type != pull_request
      osx_image: xcode8
      env: VERSION_UPGRADE_TEST_WAIT_TIMEOUT=60s

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get update -qq; fi
  - eval "CC=gcc-6 && CXX=g++-6"

env:
  global:
    - BUILD_DIR: build
    - BUILDLIB_DIR: $BUILD_DIR/libskycoin
    - LIB_DIR: lib

install:
  # Install gox
  - go get github.com/gz-c/gox
  # Install dependences for building wallet
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_PULL_REQUEST" == false ]]; then sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils && nvm install 8; fi
  - if [[ ! -d $GOPATH/src/github.com/skycoin/skycoin ]]; then mkdir -p $GOPATH/src/github.com/skycoin; ln -s $TRAVIS_BUILD_DIR $GOPATH/src/github.com/skycoin/libskycoin; fi
  - cd $GOPATH/src/github.com/skycoin/libskycoin
  # - go get -t ./...
  - make install-linters
  # Install pinned golangci-lint, overriding the latest version install by make install-linters
  - VERSION=1.10.2 ./ci-scripts/install-golangci-lint.sh
  - ./ci-scripts/install-travis-gcc.sh
  - make install-deps-libc

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$TRAVIS_PULL_REQUEST" == false ]]; then ./ci-scripts/add-key.sh; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start; fi

script:
  - make lint
  # libskycoin tests
  - CC=gcc-6 make test-libc

notifications:
  email:
    - false
  # https://github.com/kvld/travisci-telegram TravisCI Telegram Bot integration
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
